DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id int generated by default as identity (start with 1) primary key,
  username varchar(45) not null unique,
  email varchar(45) not null unique,
  gender varchar(2) not null,
  age int not null,
  date varchar(45),
  password varchar(100) not null
);